[package]
name = "pure-analyzer-parser"
description = "Parser component of the pure-analyzer workspace."
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
pure-analyzer-diagnostics.workspace = true
pure-analyzer-lexer.workspace = true
pure-analyzer-syntax.workspace = true

[dev-dependencies]
proptest.workspace = true
