[package]
name = "pure-analyzer-resolve"
description = "Resolution component of the pure-analyzer workspace."
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
